pub const TYPEHOLDER_COMMENT_PREFIX: &str = " Generated by Typeholder, DO NOT EDIT ";

pub const DEFAULT_FONTS_CONF: &str = "<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <alias>
        <!-- Generated by Typeholder, DO NOT EDIT -->
        <family>sans-serif</family>
        <prefer>
        </prefer>
    </alias>
    <alias>
        <!-- Generated by Typeholder, DO NOT EDIT -->
        <family>serif</family>
        <prefer>
        </prefer>
    </alias>
    <alias>
        <!-- Generated by Typeholder, DO NOT EDIT -->
        <family>monospace</family>
        <prefer>
        </prefer>
    </alias>
</fontconfig>
";
